# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device/device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65vice/device.proto\x12\x06\x64\x65vice\"\x1a\n\x0bReturnValue\x12\x0b\n\x03ret\x18\x01 \x01(\x03\"\x16\n\x08\x44\x65viceId\x12\n\n\x02id\x18\x01 \x01(\x04\"*\n\x0c\x44\x65viceStatus\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\x04\"+\n\x0c\x44\x65viceConfig\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xca\x01\n\nRouteGuide\x12?\n\x0fGetDeviceStatus\x12\x10.device.DeviceId\x1a\x14.device.DeviceStatus\"\x00(\x01\x30\x01\x12;\n\x0fGetDeviceConfig\x12\x10.device.DeviceId\x1a\x14.device.DeviceConfig\"\x00\x12>\n\x0fSetDeviceConfig\x12\x14.device.DeviceConfig\x1a\x13.device.ReturnValue\"\x00\x42\x1cZ\x1ago-gnet/server_grpc/deviceb\x06proto3')



_RETURNVALUE = DESCRIPTOR.message_types_by_name['ReturnValue']
_DEVICEID = DESCRIPTOR.message_types_by_name['DeviceId']
_DEVICESTATUS = DESCRIPTOR.message_types_by_name['DeviceStatus']
_DEVICECONFIG = DESCRIPTOR.message_types_by_name['DeviceConfig']
ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _RETURNVALUE,
  '__module__' : 'device.device_pb2'
  # @@protoc_insertion_point(class_scope:device.ReturnValue)
  })
_sym_db.RegisterMessage(ReturnValue)

DeviceId = _reflection.GeneratedProtocolMessageType('DeviceId', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEID,
  '__module__' : 'device.device_pb2'
  # @@protoc_insertion_point(class_scope:device.DeviceId)
  })
_sym_db.RegisterMessage(DeviceId)

DeviceStatus = _reflection.GeneratedProtocolMessageType('DeviceStatus', (_message.Message,), {
  'DESCRIPTOR' : _DEVICESTATUS,
  '__module__' : 'device.device_pb2'
  # @@protoc_insertion_point(class_scope:device.DeviceStatus)
  })
_sym_db.RegisterMessage(DeviceStatus)

DeviceConfig = _reflection.GeneratedProtocolMessageType('DeviceConfig', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECONFIG,
  '__module__' : 'device.device_pb2'
  # @@protoc_insertion_point(class_scope:device.DeviceConfig)
  })
_sym_db.RegisterMessage(DeviceConfig)

_ROUTEGUIDE = DESCRIPTOR.services_by_name['RouteGuide']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032go-gnet/server_grpc/device'
  _RETURNVALUE._serialized_start=31
  _RETURNVALUE._serialized_end=57
  _DEVICEID._serialized_start=59
  _DEVICEID._serialized_end=81
  _DEVICESTATUS._serialized_start=83
  _DEVICESTATUS._serialized_end=125
  _DEVICECONFIG._serialized_start=127
  _DEVICECONFIG._serialized_end=170
  _ROUTEGUIDE._serialized_start=173
  _ROUTEGUIDE._serialized_end=375
# @@protoc_insertion_point(module_scope)
